### ISSUE TITLE
Error message when running annotate_ehdn.sh

### ISSUE THREAD

**Issue by melnel000** [Illumina/ExpansionHunterDenovo#29] opened 2020-03-06 08:14 UTC
When running annotate_ehdn.sh I receive the following error:

awk: cmd. line:1: fatal: cannot open file `outlier_locus_annotated.tsv.temp13679.avinput.variant_function' for reading (No such file or directory)
rm: cannot remove 'outlier_locus_annotated.tsv.temp13679.avinput.exonic_variant_function': No such file or directory
rm: cannot remove '.outlier_locus_annotated.tsv.temp13679.avinput.log': No such file or directory
rm: cannot remove 'outlier_locus_annotated.tsv.temp13679.avinput.variant_function': No such file or directory

Thanks for assistance in interpreting this error message

Melissa

**Comment by mfbennett** [comment] 2020-03-06 14:58
Hi Melissa, thank you for the question!

I have seen a similar error message once, which was caused by having an incorrect filename provided to the `--annovar-annotate-variation` option, due to a typo. This should be the filename for the ANNOVAR `annotate_variation.pl` script. Could you check if this might be the problem?

Additionally, might you be able to provide some more information that may help resolve this issue? Ideally the full command that you ran and the first few lines of the outlier locus results. If you are not able to share data, feel free to email me at mark.bennett@wehi.edu.au and I can provide some test data which you could try to help debug the `annotate_ehdn.sh` script.

**Comment by melnel000** [comment] 2020-03-13 11:42
Thanks, that was indeed the problem and I am now able to run the script.

**Comment by mfbennett** [comment] 2020-03-15 12:50
Great! Closing issue now. Feel free to reopen in future if necessary.

**Closed** 2020-05-06 04:14 UTC

**Comment by CocoMlle** [comment] 2021-06-15 08:54
Hi Mark,

unfortunatly i have the same problem, i'm running this command : 
bash /work/gad/shared/bin/ExpansionHunterDenovo-v0.9.0-linux_x86_64/scripts/annotate_ehdn.sh --ehdn-results dijen1014.locus.tsv --ehdn-annotated-results annotation/dijen1014.locus.annot.tsv --annovar-annotate-variation /work/gad/shared/bin/ANNOVAR/annovar/annotate_variation.pl --annovar-humandb /work/gad/shared/bin/ANNOVAR/annovar/humandb/ --annovar-buildver hg19

i checked the filename for option -annovar-annotate-variation, i think it's ok


first lines of my tsv file : 
contig  start   end     motif   num_anc_irrs    norm_num_anc_irrs       het_str_size
chr2    70839045        70839046        AAAAAAAAAAAAAAAAAAAC    1       0.94    7
chr18   62410566        62410567        AAAAAAAAAAAAAAAAAAAC    1       0.94    7
chr19   17744455        17744456        AAAAAAAAAAAAAAAAAAAC    1       0.94    7
chr4    32563995        32563996        AAAAAAAAAAAAAAAAAAAT    1       0.94    7
chr4    139124261       139124262       AAAAAAAAAAAAAAAAAAAT    1       0.94    7
chr14   49859564        49859565        AAAAAAAAAAAAAAAAAAAT    1       0.94    7
 

do you have any ideas to help me?
thanks a lot!
Marine

**Comment by mfbennett** [comment] 2021-06-16 10:32
Hi Marine,

Thanks for using EHdn and I hope I'm able to help resolve this problem!

Are you able to share the full error message that occurs when you run the command you posted above? Either here or feel free to email me at mark.bennett@wehi.edu.au. It may help me identify what is going wrong.

One quick thing to check is whether you have downloaded the refGene annotation database. See [documentation here](https://github.com/Illumina/ExpansionHunterDenovo/blob/master/documentation/08_Annotation.md#setup-annovar) which describes how to set up ANNOVAR to run the `annotate_ehdn.sh` script.

For example, given your ANNOVAR install directory, it should look something like this:
`perl /work/gad/shared/bin/ANNOVAR/annovar/annotate_variation.pl -buildver hg19 -downdb -webfrom annovar refGene /work/gad/shared/bin/ANNOVAR/annovar/humandb/`

**Comment by hchetia** [comment] 2021-07-15 16:33
Adding a comment to this issue for future users. Sometimes we need to add "chmod +x" attribute to the annotate_variation.pl to make it work.
